FROM nginx:alpine

RUN rm /etc/nginx/nginx.conf

# Copy custom nginx config
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/conf.d/ /etc/nginx/conf.d/

# Copy SSL certificates
COPY docker/ssl-backup/ /etc/nginx/ssl/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
